<form class="recipe-form" method="post">
    <input type="hidden" name="csrf_token" value="<?= e(csrf_token()) ?>">
    <?php if (isset($id)): ?><input type="hidden" name="recipe_id" value="<?= (int) $id ?>"><?php endif; ?>
    <?php foreach ($errors as $error): ?><div class="notice notice-error"><?= e($error) ?></div><?php endforeach; ?>
    <div class="form-section"><div class="form-section-number">01</div><div><p class="eyebrow">The introduction</p><h2>Tell us about it</h2><div class="form-grid"><label>Recipe title<input type="text" name="title" value="<?= e($title) ?>" minlength="3" maxlength="150" required></label><label>Category<select name="category_id" required><option value="">Choose one</option><?php foreach ($categories as $category): ?><option value="<?= (int) $category['id'] ?>" <?= $categoryId === (int) $category['id'] ? 'selected' : '' ?>><?= e($category['name']) ?></option><?php endforeach; ?></select></label></div><label>Short description<textarea name="description" maxlength="500" minlength="10" rows="3" placeholder="What makes this recipe special?" required><?= e($description) ?></textarea></label></div></div>
    <div class="form-section"><div class="form-section-number">02</div><div class="wide-form-block"><p class="eyebrow">The grocery list</p><h2>What you will need</h2><div class="ingredient-list-editor" data-ingredients><?php foreach ($ingredients as $ingredient): ?><div class="ingredient-row"><input type="text" name="ingredients[]" value="<?= e((string) $ingredient) ?>" maxlength="255" placeholder="e.g. 1 cup coconut milk" required><button class="icon-button remove-ingredient" type="button" aria-label="Remove ingredient">×</button></div><?php endforeach; ?></div><button class="add-ingredient" type="button" data-add-ingredient>+ Add another ingredient</button></div></div>
    <div class="form-section"><div class="form-section-number">03</div><div><p class="eyebrow">The method</p><h2>How to make it</h2><label class="sr-only" for="instructions">Cooking instructions</label><textarea id="instructions" name="instructions" maxlength="10000" minlength="10" rows="12" placeholder="Write each step on a new line..." required><?= e($instructions) ?></textarea></div></div>
    <div class="form-submit"><button class="button button-primary" type="submit"><?= isset($id) ? 'Save changes' : 'Publish recipe' ?> <span aria-hidden="true">↗</span></button><a class="text-link" href="<?= isset($id) ? 'recipe.php?id=' . (int) $id : 'index.php' ?>">Cancel</a></div>
</form>
